name: TACTLib
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    submodules: 'recursive'
            -   name: Install .NET 8
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 8.0.x
            -   name: Restore project
                run: dotnet restore TACTLib.sln --verbosity m -r win-x64
            -   name: Build Release
                run: dotnet publish -f net8.0 --configuration Release -r win-x64 --self-contained false -o dist/Release
            -   name: Upload Release
                uses: actions/upload-artifact@v2
                with:
                    name: TACTLib-release
                    path: dist/Release
            -   name: Build Debug
                run: dotnet publish -f net8.0 --configuration Debug -r win-x64 --self-contained false -o dist/Debug
            -   name: Upload Debug
                uses: actions/upload-artifact@v2
                with:
                    name: TACTLib-debug
                    path: dist/Debug
